name = "{{.ProjectName}}"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat_v2"]

[[d1_databases]]
binding = "DB"
database_name = "api-db"
database_id = "local-mock"

[[kv_namespaces]]
binding = "CACHE"
id = "local-kv"

[[queues.producers]]
binding = "QUEUE"
queue = "local-queue"


