name = "{{.ProjectName}}"

[main]
path = "api/index.ts"

[[functions]]
name = "auth-hook"
path = "functions/auth-hook.ts"
route = "/auth/*"

{{if .IsD1}}
[[d1_databases]]
binding = "DB"
database_name = "{{.ProjectName}}-db"
{{end}}

[[kv_namespaces]]
binding = "CACHE"
id = "local-kv"

[[queues.producers]]
binding = "QUEUE"
queue = "local-queue"

{{if .IsNeon}}
[[postgres_databases]]
binding = "PG"
connection_string = "$DATABASE_URL"
{{end}}
