name = "{{.ProjectName}}"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat_v2"]

[[postgres_databases]]
binding = "PG"
connection_string = "$DATABASE_URL"
pool_size = 10

[[kv_namespaces]]
binding = "CACHE"
id = "local-kv"

[[queues.producers]]
binding = "QUEUE"
queue = "local-queue"
