name = "{{.ProjectName}}"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "api-db"
database_id = "local-mock"

[[kv_namespaces]]
binding = "CACHE"
id = "local-kv"

[[queues.producers]]
binding = "QUEUE"
queue = "local-queue"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "api-db"
database_id = "YOUR_STAGING_D1_ID"

[[env.production.d1_databases]]
binding = "DB"
database_name = "api-db"
database_id = "YOUR_PRODUCTION_D1_ID"
