name = "{{.ProjectName}}"
main = "src/index.ts"
compatibility_date = "2025-09-01"

[[d1_databases]]
binding = "DB"
database_name = "api-db"
database_id = "local-mock"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "api-db"
database_id = "YOUR_STAGING_D1_ID"

[[env.production.d1_databases]]
binding = "DB"
database_name = "api-db"
database_id = "YOUR_PRODUCTION_D1_ID"
